[package]
name = "hello_blinky_board"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
critical-section = "1.1.2"
fugit = "0.3.7"
panic-halt = "0.2.0"
rp-pico = "0.8.0"
hello_blinky_driver = {path = "../driver"}
embedded-hal = "0.2.7"
